# [![Deploy Jekyll with GitHub Pages dependencies preinstalled](https://github.com/Elparadisogonzalo/Assets3/actions/workflows/jekyll-gh-pages.yml/badge.svg)](https://github.com/Elparadisogonzalo/Assets3/actions/workflows/jekyll-gh-pages.yml).github/dependabot.yml
version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/" # Location of .github/workflows
    schedule:
      interval: "weekly"

  # NPM (Node.js) dependencies
  - package-ecosystem: "npm"
    directory: "/" # Change if your package.json is in a subdirectory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
